# For more information about the available options please visit: http://go/catalog-info (VPN required)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: Unity-Technologies/terraform-google-certificate-map-simple-internal
    backstage.io/techdocs-ref: dir:.
  name: terraform-google-certificate-map-simple-internal
  description: "Simple creation of GCP Cloud Certificate Manager maps"
  labels:
    costcenter: "7151"
spec:
  type: service
  lifecycle: experimental
  owner: Unity-Technologies/unity-services-foundation
